# Site settings
title: Marlon Somwaru
description: A blog about lorem ipsum dolor sit amet
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Marlon Somwaru
user_description:  I'm currently a student at Queens College, persuring a BA in Computer science.  In 2019, I graduated from Baruch College with a dual degree in Mathematics and Economics.  This decision came from being absolutely terrible at math in high school, and struggling to understand what I was hearing on the news.  This gave me ability to approach problems from both an analytical and conceptual stand point.  It also sparked my interest in data science and artificial intelligence.

In our day and age, we have a tremendous amount of data and not enough people who can understand it.  It's no longer enough to be a good programmer, a math whiz, or a statistician.  It is crucial to be able to combine all of these things to extract, formulate, and tell a story. 

My goal is to tell a captivating story with the work I do and hopefully inspire others to tell their own.
user_title: Aspiring Machine Learning Engineer
email: marlon.somwaru@gmail.com
github_username:  MarlonSomwaru
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
